### PR TITLE
switch to new karabiner.json location

### PR DESCRIPTION
**Pull request by noopkat**
👋 Hello!

Love this package; really useful thank you! 👍 

The recent version of Karabiner Elements moved the `karabiner.json` file to [a slightly different location](https://github.com/tekezo/Karabiner-Elements/tree/master/usage#learn-about-karabinerjson) within `$HOME`. I updated this package to reflect the new dir location.

Thanks again 🙇‍♀️ and happy new year! 🎆

### CODE REVIEW

**Comment by kenotron** [comment]
I've not used this utility ever since I found a switch to turn off Karabiner for certain devices (like the Apple keyboard). I'll verify this today and merge :)

**Comment by noopkat** [comment]
no worries! I use several keyboards for different purposes, so switching profiles is really useful for me still. Appreciate it!

**Comment by kenotron** [comment]
Verified!

**Comment by kenotron** [comment]
Thanks for the PR :)

**Pull request merged**
